ARG baseImageTag
ARG baseImageUri
FROM ${baseImageUri}:${baseImageTag}

ARG version
ARG mavenArtifactBaseUrl
ARG camunda_liquibase_version=17.21.4
ARG wildfly_home=/opt/jboss/wildfly
ARG wildfly_user=jboss
ARG context_group_name=work-management-proxy
ARG context_name=work-management-proxy-api
ARG framework_version

ADD ${mavenArtifactBaseUrl}/uk/gov/moj/cpp/${context_group_name}/${context_name}/${version}/${context_name}-${version}.war ${wildfly_home}/standalone/deployments/
USER root
RUN chown -R ${wildfly_user}:${wildfly_user} ${wildfly_home}/standalone/deployments/ && chmod -R 700 ${wildfly_home}/standalone/deployments/

# liquibase jars & config
RUN mkdir /tmp/liquibase
ADD ${mavenArtifactBaseUrl}/uk/gov/moj/cpp/camunda/camunda-liquibase/${camunda_liquibase_version}/camunda-liquibase-${camunda_liquibase_version}.jar /tmp/liquibase/camunda-liquibase.jar
RUN chmod -R 755 /tmp/liquibase
COPY scripts/liquibase.sh /tmp/liquibase/liquibase.sh
RUN chown ${wildfly_user}:${wildfly_user} /tmp/liquibase/liquibase.sh && chmod 755 /tmp/liquibase/liquibase.sh
USER ${wildfly_user}
LABEL base_image ${baseImageTag}
